
version: 2

jobs:
  test:
    docker:
      - image: circleci/node:6.13-stretch
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  version: 2
  test:
    jobs:
      - test