version: 0.2

env:
  parameter-store:
    NPM_TOKEN: {{parameter_prefix}}.npmToken

phases:
  pre_build:
    commands:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
  build:
    commands:
    - npm publish
